COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/Board.cpp
COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/Logging.cpp
COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/CanRxThread.cpp
COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/CanTxThread.cpp
COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/CanProtocol.cpp
