COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/Board.cpp
COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/Logging.cpp
COMMONCPPSRC += $(SOURCEDIR)/$(TARGET_TYPE)/$(TARGET)/BoardSpecific.cpp

COMMONINC += $(SOURCEDIR)/$(TARGET_TYPE)
